
class DependencyError(Exception): ...

class DeclarationError(DependencyError): ...
class ResolutionError(DependencyError): ...

# TODO: Añadir excepciones específicas para condicioens de inicialización
