from dependency.core.exceptions import ResolutionError as ResolutionError
from dependency.core.injection.injection import ProviderInjection as ProviderInjection
from dependency.core.utils.cycle import find_cycles as find_cycles
from typing import Iterable

def raise_circular_error(providers: Iterable[ProviderInjection]) -> bool: ...
def raise_dependency_error(unresolved: Iterable[ProviderInjection]) -> bool: ...
def raise_resolution_error(providers: Iterable[ProviderInjection], unresolved: Iterable[ProviderInjection]) -> None: ...
